### ISSUE TITLE
Download the GFF file of the Cycas taitungensis mitochondrion

### ISSUE THREAD

**Issue by sjackman** [bionode/bionode-ncbi#11]
Hi. I'd like to download the annotation in GFF format of the _Cycas taitungensis_ mitochondrion, [NC_010303.1](http://www.ncbi.nlm.nih.gov/nuccore/166895601). I started with `bionode ncbi search genome cycas taitungensis`, but got nada back. Any suggestions?

**Comment by bmpvieira** [comment]
Hi, there's no ncbi "genome" or "assembly for *Cycas taitungensis*, but you can download the Genbank file and convert it to GFF, or just use [togows.org](http://togows.org) to get it directly using the NCBI ID:

```bash
bionode-ncbi search nuccore NC_010303.1 | json uid | while read id; do wget http://togows.org/entry/nucleotide/$id.gff; done
```

**Comment by sjackman** [comment]
Perfact! Thanks, Bruno.

http://togows.org/entry/nucleotide/166895601.gff

**Comment by sjackman** [comment]
For future me, or someone else, here's my Makefile snippet:

```Makefile
# Cycas taitungensis
NC_010303.1.json: %.json:
	bionode-ncbi search nuccore $* >$@

%.uid: %.json
	json uid <$< >$@

%.fa: %.uid
	curl http://togows.org/entry/nucleotide/`<$<`.fasta |seqtk seq >$@

%.gb: %.uid
	curl -o $@ http://togows.org/entry/nucleotide/`<$<`.gb

%.gff: %.uid
	curl -o $@ http://togows.org/entry/nucleotide/`<$<`.gff
```

**Comment by sjackman** [comment]
`npm install -g bionode bionode-ncbi json`

**Comment by bmpvieira** [comment]
Thanks @sjackman for your comments. I haven't closed this yet because it could be a nice thing to add to bionode. /cc @terfn

**Comment by bmpvieira** [comment]
@terfn recently added NCBI efetch to bionode, so soon something like this should work:

```bash
echo -e "{'db': 'nuccore', 'term': 'NC_010303.1', 'rettype': 'fasta'}\n" | bionode-ncbi fetch -
```

It currently doesn't because of the way CLI is parsing things, but in JavaScript the following works and gives a fasta:

```javascript
var ncbi = require('bionode-ncbi')
var fasta = require('bionode-fasta')
var json = require('JSONStream')

var opts = {
  db: 'nuccore',
  term: 'NC_010303.1',
  rettype: 'fasta'
}

ncbi.fetch(opts)
.pipe(json.stringify()) // We shouldn't need this, bionode-fasta should accept objects
.pipe(fasta.write())
.on('data', function (data) {
  console.log(data)
})
```

**Comment by terfn** [comment]
By the way fasta is the default rettype for nuccore and some other dbs so it's not necessary to specify it. Also it is possible to get the GenBank flat file format from nuccore using efetch by specifying 

```
retype: 'gbwithparts'
```

If the goal is to convert it to a GFF later

@bmpvieira I'll take a look at making the CLI accept objects

**Comment by bmpvieira** [comment]
After https://github.com/bionode/bionode-ncbi/pull/32 is merged, this should work:
```bash
echo -e '{"term": "NC_010303.1", "rettype": "fasta"}' | bionode-ncbi fetch nuccore -s
```

**Comment by sjackman** [comment]
Nice. Thanks, Bruno!
