### ISSUE TITLE
We need a smaller assembly from NCBI for testing

### ISSUE THREAD

**Issue by bmpvieira** [bionode/bionode-ncbi#24]
*Guillardia theta* assembly file is around 50mb. This wasn't a problem when the tests were downloading it every time from NCBI. However, now we are mocking NCBI api with a cached version of the file (so that tests don't break every week due to NCBI side changes). So this file is now stored in git-lfs, and with TravisCI testing we quickly reach the 1GB/month free GitHub git-lfs bandwidth. Maybe there's a small virus, bacteria or DNA region on NCBI with a much smaller assembly.

**Comment by tiagofilipe12** [comment]
For instance: ```bionode-ncbi download assembly Stenotrophomonas acidaminiphila```

**Comment by tiagofilipe12** [comment]
Even better: _Stenotrophomonas ginsengisoli_ has 966.23 kB

**Comment by tiagofilipe12** [comment]
I actually found a more decent assembly from a small bacteria (_Carsonella ruddii_).
