### ISSUE TITLE
Use progress bar on download

### ISSUE THREAD

**Issue by Fohlen** [bionode/bionode-ncbi#40]
It would be better to use a progress bar when downloading archives.
Only when using a `--verbose` flag all details should be printed to the console.

**Comment by Istar-Eldritch** [comment]
Hi @Fohlen, I think I don't understand exactly what you mean. There is already a download progress bar when using the `download` subcommand. Where would you like to see this feature?

**Comment by Fohlen** [comment]
Hey @Istar-Eldritch for `bionode-ncbi@2.0.1` on OSX High Sierra this is not exactly the case.
I do get all the file names and everything printed in my console when using the download subcommand.

**Comment by Istar-Eldritch** [comment]
Interesting... Would you be able to provider a recording of the case? The output of https://asciinema.org/ or a gif recorder would come handy to see the reproduction details. I don't have a mac with me now but I'll try to reproduce it Monday.

**Comment by Fohlen** [comment]
Hey @Istar-Eldritch, have a look here
https://asciinema.org/a/dq6MNldxau5fBMXrJL5AdbgRl

This ofc goes on and on for the entire archive 🚀

**Comment by Istar-Eldritch** [comment]
Thank you very much for the video. :)

If you add the `--pretty` flag you should get the expected progress bar:
`bionode-ncbi download assembly human --pretty`

Bionode benefits from its streaming capabilities, making it composable with other command line utilities though Unix pipes. In the case of download, I guess the decision of keeping the output in NDJSON was to keep the interface coherent with the behaviour of the rest of the CLI.

I hope this clarifies a bit your issue.
